### ISSUE TITLE
rendered: Stary nazov obce Soblahov

### ISSUE THREAD

**Issue by petervojtek** [FreemapSlovakia/FreemapBackend#1]
mapa stale zobrazuje "Soblahov 552":
http://www.freemap.sk/#p=48.86448|18.0805|15|T

aj ked kayle to uz pred mesiacom opravil na Soblahov:
https://www.openstreetmap.org/node/26038426/history#map=18/48.86437/18.07706

<img width="393" alt="screenshot 2016-11-15 09 17 30" src="https://cloud.githubusercontent.com/assets/225506/20298207/df77ac40-ab14-11e6-9cb0-f3da7e0b262e.png">

**Comment by tjamecny** [comment]
Renderovanie nazvov sa vykonava "obcasne", t.j. asi raz za 2 mesiace. Po poslednej aktualizacii je uz chyba odstranena.
