### ISSUE TITLE
API endpoint: nahrat/ziskat GPX trasu

### ISSUE THREAD

**Issue by petervojtek** [FreemapSlovakia/FreemapBackend#11]
tu je [zodpovedajuca issue pre frontend](https://github.com/FreemapSlovakia/freemap-v3-react/issues/101)

pouzivatel cez [nastroj prehliadac tras](http://next.freemap.sk/) nahra GPX, ta sa zobrazi. v menu pri zobrazenej trase by sme chceli mat tlacidlo "zdielat odkaz na trasu" ktore vygeneruje url. na to potrebujeme gpx nahrat na server a neskor ho zase ziskat.

### Nahrat GPX

```
POST /tracklogs/
```

request body bude JSON:

```
{
   "b64data": <string - b64 enkodovane gpx>,
   "format": "application/gpx+xml",
   "name": <nazov povodneho suboru>
  }
```

response bude JSON:

```
{"uid": <string>}
```

UID by mohlo mat povedzme 8 znakov ([a-zA-Z0-9]), lebo ho budeme davat do url.

### Ziskat GPX

```
GET /tracklogs/<uid>
```

v response body vrati json:

```
{
   "uid": <uid>,
   "b64data": <string - b64 enkodovane gpx>,
   "format": "application/gpx+xml",
   "name": <nazov povodneho suboru>
  }
```

### Ine

* Na starom freemape sa mi nepodarilo najst kde sa da nahrat GPX
* na frontende gpx konvertujeme na geojson a pracujeme s iba s geojson. technicky by sme vedeli namiesto gpx uploadovat geojson (a usetrit si druhu konverziu gpx-geojson pri get-e), ale zda sa mi vhodnejsie uploadnut povodne gpx, lebo pri konverzii gpx->gejson sa moze cast informacii stratit.
* zvolil som B64 enkodovanie gpx-ka, aby to vedelo byt bez problemov cele v json-e. inak sa da aj priamo xml (gpx) vlozit do json-u, ale by sme si museli  davat pozor na escapovanie uvodzoviek, s b64 je to bezstarostnejsie).
* frontend vieme lahko rozsirit aby pouzivatel mohol nahrat aj viac gpx suborov naraz. api pre ten ucel budeme moct ponechat ake je, len budeme robit viac requestov (a share url neskor mozno bude vyzerat `next.freemap.sk/share/tracklog/?uid=<uid1>,<uid2>`)
* frontend vieme lahko rozsirit aby podporovat aj kml -- potom len v api volani zmenime `format` parameter

**Comment by zdila** [comment]
Upravil by som API aby bolo "viac restful"

* namiesto `POST` dat `PUT`
* cestu upravit na `/tracklogs/` a `/tracklogs/<tracklog_id>`

Osobne by som nove API rad implementoval v https://github.com/FreemapSlovakia/freemap-v3-api. Ak si najdem cas (uz mesiac sa stahujeme) tak sa k tomu hadam dostanem.

**Comment by tjamecny** [comment]
Tiez mi chvilu trvalo, kym som to nasiel a pritom jej to priamo na hlavnej mape v lavom dolnom rohu (na mensom monitore v podstate az v strede):
![fm_nahrat_gpx](https://cloud.githubusercontent.com/assets/16599347/24851257/5082c6e6-1dd3-11e7-8f08-40dbe2d19ee8.png)

Funguje to trochu neocakavane, lebo po zvoleni suboru si to javascriptom automaticky cez POST posle subor na server, hoci by som ocakaval, ze sa tak stane az po stlaceni tlacidla "spracovat log".

Otazky:
1) ako bude fungovat prihlasenie (vseobecne), kedze pri 8 znakovom identifikatore nie je problem si vytiahnut aj privatne trasy. Tie by sme mohli vraciat iba vtedy, ak bude v requeste aj <sessionId>, z ktorej si viem na serveri zistit <uzivatelID> a ten sa musi zhodovat s uzivatelom danej privatnej trasy.
2) znaky v ID su predpokladam case-sensitive, t.j. 123456AB bude ine ID trasy ako 123456ab

**Comment by petervojtek** [comment]
> cestu upravit na /tracklogs/ a /tracklogs/<tracklog_id>

suhlasim 

> namiesto POST dat PUT

mozno som nieco nepochopil, ale na to aby to bolo restful cez PUT by sme museli ID generovat na frontende nie? (aby sme mohli robit idempotentne `PUT tracklogs/123`)

> Osobne by som nove API rad implementoval v https://github.com/FreemapSlovakia/freemap-v3-api. 

nerozumiem aky je/ma byt vztah medzi tym co robi Tibor a tym co zamyslas vo freemap-v3-api

> ako bude fungovat prihlasenie (vseobecne), kedze pri 8 znakovom identifikatore nie je problem si vytiahnut aj privatne trasy

mozeme dat aj dlhsie identifikator. inak ked tam raz bude prihlasovanie, tak si predstavujem JSON pre `POST tracklogs` rozsirime aj o atributy `owner` a `visibility` (private/anyone-with-share-url/public)

> znaky v ID su predpokladam case-sensitive

myslel som to ako case sensitive (aby sme mohli mat kratsi uid string)

**Comment by zdila** [comment]
> kedze pri 8 znakovom identifikatore nie je problem si vytiahnut aj privatne trasy

16^8 = 4 294 967 296 - manualne tazko trafis cislo, ale nejakym toolom by sa dalo :-). Ak by sme mali v systeme milion tras, tak nahodnym triafanim IDciek mas 0.023 % sancu ze sa nieco urodi.

Ja zvyknem pouzivat BASE62 enkodovane UUIDcka (https://www.npmjs.com/package/uuid-base62).

> znaky v ID su predpokladam case-sensitive

jednoznacne.

**Comment by zdila** [comment]
> ale na to aby to bolo restful cez PUT by sme museli ID generovat na frontende nie?

mas pravdu, prehliadol som. beriem s5.

> nerozumiem aky je/ma byt vztah medzi tym co robi Tibor a tym co zamyslas vo freemap-v3-api

freemap-v3-api ma byt nova implementacia API zalozena na nodejs, teda aby som do nej vedel prispievat aj ja, kedze do PHP nebudem.

**Comment by petervojtek** [comment]
> freemap-v3-api ma byt nova implementacia API zalozena na nodejs, teda aby som do nej vedel prispievat aj ja, kedze do PHP nebudem.

toto by asi bolo vhodne keby ste si s Tiborom vyjasnili -- z mojho pohladu nie je problem ked sa na niecom zacne robit napr. o mesiac (lebo sa stahujes)..vonku je pekne a viem sa zabavit aj bez programovania freemap-u :)

inak -- o mesiac na mapping party na Taloch a mohli by sme si tam dat nejaku session ohladom freemap-3 (ja nie som v zozname ubytovanych, ale budem tam, kedze mam nehnutelnost kusok vedla).

**Comment by zdila** [comment]
> toto by asi bolo vhodne keby ste si s Tiborom vyjasnili

Tak zase backend moze byt implementovany roznymi technologiami - nejaka featura v nodejs a nejaka v PHP / perl / python / whatever :-). Ako nezavisle "microservices" ktore budu zdielat DB. A mozno sa potom postupne budu migrovat veci z PHP do nodejs. Klientovi to je jedno, kym je API napisane dobre.

> by sme si tam dat nejaku session ohladom freemap-3 

suhlas

**Comment by petervojtek** [comment]
> nejaka featura v nodejs a nejaka v PHP / perl / python / whatever

**Comment by petervojtek** [comment]
tuto funkcionalitu budeme riesit v node.js backende, tu je prisusna issue:
https://github.com/FreemapSlovakia/freemap-v3-api/issues/1
