### ISSUE TITLE
Pridávanie fotografií do galérie

### ISSUE THREAD

**Issue by synalik** [FreemapSlovakia/FreemapBackend#13]
Pri pridávaní fotografií, ktoré sú ogeotagované systém automaticky nerozpozná súradnice. Skúšané v Chrome, Vivaldi a Maxthorn. Nahrávanie fotky trvá neskutočne dlho. Megabajtovú fotku sa mi podarilo nahrať asi na 5 pokus - veľa krát po dvoch troch minútach stále píše "nahrávam", tak to zruším a nanovo.
Pri pridávaní fotky by sa nedalo zjednodušiť pridanie do kategórie tým, žeby bola vyberateľná z rolovacieho Menu?

**Comment by zdila** [comment]
> Pri pridávaní fotografií, ktoré sú ogeotagované systém automaticky nerozpozná súradnice

Prosim prilozit problematicku fotku.

> Nahrávanie fotky trvá neskutočne dlho

Prosim otestovat rychlost svojho uplinku. Mne 4 MB fotku uploadne cca za sekundu.

> Pri pridávaní fotky by sa nedalo zjednodušiť pridanie do kategórie tým, žeby bola vyberateľná z rolovacieho Menu?

Po napisani dvoch pociatocnych pismen saq zjavi rolovacie menu, ak dany tag najde. Zatial sme lepsi komponent nenasli, ale vlastnej iniciative sa medze nekladu. Musi splnat podmienku, ze je pisany pre React.

**Comment by zdila** [comment]
Inac tyka sa to stareho Freemapu? Lebo tento projekt je pre stare Freemap API. Pre next.freemap.sk su projekty:
* backend (API): https://github.com/FreemapSlovakia/freemap-v3-nodejs-backend a cast do
* forntend (web appka): https://github.com/FreemapSlovakia/freemap-v3-react

**Comment by synalik** [comment]
vzorka foto:
![cyklo 002_2010](https://user-images.githubusercontent.com/26544966/30347674-26e5adee-980d-11e7-94e8-778b56234f8f.JPG)

rýchlosť
![rychlost](https://user-images.githubusercontent.com/26544966/30347784-798c3126-980d-11e7-90bf-65fb02eb589e.jpg)

týka sa to nového next.freemap.sk

**Comment by zdila** [comment]
> Pri pridávaní fotografií, ktoré sú ogeotagované systém automaticky nerozpozná súradnice

Pridal som "hack" pre parsovanie GPS suradnic z toho Olympusu. Pouzita EXIF kniznica ich nevedela rozparsovat.

> Pri pridávaní fotky by sa nedalo zjednodušiť pridanie do kategórie tým, žeby bola vyberateľná z rolovacieho Menu?

Vytvoril som https://github.com/FreemapSlovakia/freemap-v3-react/issues/206

> Nahrávanie fotky trvá neskutočne dlho

Skus v Chrome network tabe pozriet ci tam nemas nieco podozrive. Pripadne posli screenshot ako tento:

![image](https://user-images.githubusercontent.com/636095/30349517-8b4b9a22-9813-11e7-9cf4-8f89a75324db.png)

Tuto issue zatvaram.
