### ISSUE TITLE
rendered: uvodzovky z tagu name su "escapnute"

### ISSUE THREAD

**Issue by petervojtek** [FreemapSlovakia/FreemapBackend#2]
http://www.freemap.sk/#p=48.59667|17.60367|16|T
https://www.openstreetmap.org/way/4354642

<img width="579" alt="screenshot 2016-11-15 09 23 47" src="https://cloud.githubusercontent.com/assets/225506/20298267/3a7e84ba-ab15-11e6-9900-889733918b45.png">

**Comment by tjamecny** [comment]
Po naimportovaní nových OSM dát v polovici januára už v príslušných tabuľkách v DB nie sú HTML entity. Pri predspracovaní dát pre výpočet polohy POI a názvov došlo k chybe (kvôli neescapnutému apostrofu) a preto sa použila predchádzajúca sada dát, ktorá ešte obsahuje HTML entity. Po ďalšom spustení výpočtu polohy POI & názvov opäť skontrolujem, či je už táto chyba odstránená. Zatiaľ ponechávam v stave "open".

**Comment by tjamecny** [comment]
Chyba vyzerá byť konečne odstránená, zatváram.
