### ISSUE TITLE
Pridať podporu CORS

### ISSUE THREAD

**Issue by zdila** [FreemapSlovakia/FreemapBackend#3]
Pre testovanie zatiaľ z domény `freemapslovakia.github.io` (https://freemapslovakia.github.io/freemap-v3-react-dist/) a `localhost`, prípadne z nejakej lokálnej, ktorú si pridáme do `hosts`, napr. `freemap.local`.

**Comment by tjamecny** [comment]
Možeš prehodiť vyhľadávanie na freemap, aby som mohol debugovať CORS?

**Comment by zdila** [comment]
routovanie je cez freemap (cez https://www.freemap.sk/api/...)
a este bude treba aj https://dev.freemap.sk/api/...

**Comment by tjamecny** [comment]
Aktuálne plánovač trasy funguje korektne cez www API. Snažím sa ale nájsť spôsob (momentálne kvôli tomu rozbíjam dev), ako pridať podporu CORS centrálne (napr. v index.php), aby sa neopakoval ten istý kód v každom PHP skripte v /api/ adresári. Zatiaľ ponechávam túto Issue otvorenú.

**Comment by tjamecny** [comment]
CORS povolené v .htaccess na dev/prod pre HTTP/HTTPS requesty na /api/ z:
- *.freemap.sk
- freemapslovakia.github.io
- localhost
- freemap.local

Routing na fm.github.io funguje, zatváram Issue.
