### ISSUE TITLE
api endpoint pre planovac trasy

### ISSUE THREAD

**Issue by petervojtek** [FreemapSlovakia/FreemapBackend#5]
aktualne na freema3 pouzivame `https://www.freemap.sk/api/0.1/r/` -- vcelku je to fajn, az na to ze to vracia xml.

novy endpoint by mohol vyzerat takto:

```
GET /route-planner/<body_trasy>/?transport_type=<car/bicycle/walk>
```

* `body_trasy` -- jednoduchy zoznam lat lons oddelene ciarkami, kde prva lat lon je start, posledna latlon je ciel a ak su nejake dalsie latlons medzi nimi, to su medzizastavky. napr: 
  * `49.0,17.1,50.1,17.2` znamena ze mame iba start a ciel
  * `49.0,17.1,44.4,17.7,50.1,17.2` znamena ze mame start, jednu zastavku a  ciel
* `transport_type` jedno z `car, bicycle, walk`. aktualne freemap rozlisuje `peso` a `turistika`, neviem aky ma byt medzi tym rozdiel, podla mna je to z UI hladiska matuce.
* nie je mi jasne ci chceme zavadzat aj parameter najrychlejsia/najkratsia, podla mna to pouzivatelov skor matie a komplikuje to UI.

response je json, samotna trasa je geojson:

```
{
  "route": {
    "geometry": {
      "type": "LineString",
      "coordinates": [[49.0, 10.1], [47.0, 11.1], [48.0, 11.1]]   // vysledna trasa
    },
    "properties": {
      "distance_in_km": 11.3,
      "duration_in_minutes": 145 ,
      "itinerary": [
            {"point": [49.0, 10.1], "desc": "zaboc vlavo", "distance_from_start_in_km": 4.5},
            {"point": [47.0, 11.1], "desc": "zaboc vpravo", "distance_from_start_in_km": 6.2}
         ]
    }
  }
}
```

itinerar na uvod robit nemusime, ale ked uz ho tam budeme mat, pacilo by sa mi keby tak ako som navrhol poskytoval informaciu o bode v ktorom sa dana akcia itinerara odohrava, co by v GUI vyzeralo takto:  pouzivatelovi sa zobrazi zoznam z itineraru, a ked prejde mysou ponad niektoru polozku (napr. "na krizovatke odboc vlavo), rozsvieti sa prislusny bod planovanej trasy.

**Comment by tjamecny** [comment]
Freemap rozlišuje pešo/turistika preto, že v režime turistika uprednostňuje cesty, ktoré sú v TZT reláciách. Toto nemusí momenálne fungovať na 100%, nakoľko máme zastarané informácie v Gosmore, ktorý sa používa na výpočet trasy (bude opravené v blízkej budúcnosti).

Úplné minimum parametrov v requeste je len zoznam bodov (vtedy sa použije režim "fastest" a ako prostriedok "car"): http://www.freemap.sk/api/0.3/route-planner/49.12234,18.68378,49.1228,18.68737 

Vypnutie "fastest" režimu sa dá spraviť cez parameter "&variant=shortest". Parameter "transport_type" funguje ako bolo požadované, len som ponechal aj hodnotu "hiking". Posledné lomítko nie je potrebné uvádzať ani vtedy, keď sú špecifikované nejaké parametre (napr. transport_type).

**Comment by petervojtek** [comment]
ok, osvojili sme si to cez #92.
dalsie zmeny by sme mohli riesit cez separatne issues a preto tuto issue zatvaram.
