### ISSUE TITLE
Pridať podporu CORS aj pre porty iné ako 80

### ISSUE THREAD

**Issue by zdila** [FreemapSlovakia/FreemapBackend#6]
Napr. ak v requeste je `Origin: http://local.freemap.sk:8080` tak nevrati ziadnu `Access-Control-Allow-Origin`. Kudne to povol napr iba pre `localhost` a `freemap.local`, alebo pre vsetky :-)

**Comment by tjamecny** [comment]
O portoch v #3 nepadla ani zmienka, preto som sa tomu nevenoval :)
Pridal som podporu do dev/prod pre všetky povolené domény, aj som otesoval na kombinácii github.io+port.
